# Generated by Django 5.0.3 on 2024-03-17 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_options_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availabile',
            new_name='available',
        ),
    ]
